{
 "title": "EW benchmarks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "E-W(Across AZs)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*(foo_egress_http_requests_seconds{appId=\"ewbenchmark\",job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"ns-personal-shibmish\",status=\"200\",upstream=\"http://bar-service.ns-personal-shibmish.svc.cluster.local/bar/hello\"})"
    }
   ]
  },
  {
   "title": "E-W(Same Node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*(foo_egress_http_requests_seconds{appId=\"ewbenchmark\",job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"ns-personal-shibmish\",status=\"200\",upstream=\"http://foo-friend-service.ns-personal-shibmish.svc.cluster.local/bar/hello\"})"
    }
   ]
  },
  {
   "title": "Adobe I/O Egress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*(foo_egress_http_requests_seconds{appId=\"ewbenchmark\",job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"ns-personal-shibmish\",status=\"200\",upstream=\"https://k8slighthousesvc-dev-va6.adobe.io/bar/hello?api_key=asrexample\"})"
    }
   ]
  },
  {
   "title": "Ethos Public Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*(foo_egress_http_requests_seconds{appId=\"ewbenchmark\",job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"ns-personal-shibmish\",status=\"200\",upstream=\"http://shibu-bar.sandbox.cloud.adobe.io/bar/hello\"})"
    }
   ]
  },
  {
   "title": "Fixed Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*(foo_egress_http_requests_seconds{appId=\"ewbenchmark\",job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"ns-personal-shibmish\",status=\"200\",upstream=\"http://shibu-bar.sandbox.cloud.adobe.io/bar/delay?delay=300\"})"
    }
   ]
  }
 ]
}